eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

server:
  port: 10002

spring:
  application:
    name: buyer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent_output: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://108.160.140.18:3306/Buyer
    username: developer
    password: cuiyicong
